# generated by datamodel-codegen:
#   filename:  openapi/powercontext.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    model_validator,
)


class ArtifactReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]


class ArtifactAddress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class PublishArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: ArtifactAddress
    target_scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    idempotency_key: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ArtifactPublication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: ArtifactAddress
    target: ArtifactAddress
    content_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]


class ScopeExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    value: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]


class ContextReference(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: list[ContextReference]
    external_references: list[ScopeExternalReference]
    version: Annotated[StrictInt, Field(ge=1)]


class ScopePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[ScopeDescriptor]


class CreateScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: Annotated[list[ContextReference], Field(validate_default=True)] = []
    external_references: Annotated[list[ScopeExternalReference], Field(validate_default=True)] = []
    idempotency_key: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class UpdateScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_version: Annotated[StrictInt, Field(ge=1)]
    title: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    summary: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]
    parent_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    context_references: Annotated[list[ContextReference], Field(validate_default=True)] = []
    external_references: Annotated[list[ScopeExternalReference], Field(validate_default=True)] = []


class SetDefaultScopeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class Mode(StrEnum):
    ALL = "all"


class AllScopeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["all"]


class Mode1(StrEnum):
    EXACT = "exact"


class ScopeId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ExactScopeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["exact"]
    scope_ids: Annotated[list[ScopeId], Field(min_length=1)]


class Mode2(StrEnum):
    SUBTREE = "subtree"


class SubtreeScopeSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: Literal["subtree"]
    root_scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeSelection(RootModel[AllScopeSelection | ExactScopeSelection | SubtreeScopeSelection]):
    root: Annotated[AllScopeSelection | ExactScopeSelection | SubtreeScopeSelection, Field(discriminator="mode")]


class ResolveScopeSelectionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selection: ScopeSelection


class ScopeBindingKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    integration: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    kind: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern=".*\\S.*")]
    external_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ScopeBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: ScopeBindingKey
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class SetScopeBindingRequest(RootModel[ScopeBinding]):
    root: ScopeBinding


class ClearScopeBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: ScopeBindingKey


class ClearScopeBindingResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cleared: StrictBool


class ResolveScopeBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    explicit_scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1, pattern=".*\\S.*")] = None
    binding_keys: Annotated[list[ScopeBindingKey], Field(validate_default=True)] = []


class CandidatePermissions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    can_revise: StrictBool
    can_approve: StrictBool
    can_reject: StrictBool


class ApproveArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]


class FamilyCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    total: Annotated[StrictInt, Field(ge=0)]


class MemoryKindCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    total: Annotated[StrictInt, Field(ge=0)]
    active: Annotated[StrictInt, Field(ge=0)]
    inactive: Annotated[StrictInt, Field(ge=0)]


class SourceInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    memory_processed: Annotated[StrictInt, Field(ge=0)]
    memory_pending: Annotated[StrictInt, Field(ge=0)]


class ArtifactInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    by_family: list[FamilyCount]


class MemoryEntryInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    active: Annotated[StrictInt, Field(ge=0)]
    inactive: Annotated[StrictInt, Field(ge=0)]
    by_kind: list[MemoryKindCount]


class MemoryInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: MemoryEntryInventoryStatistics


class ModelUsageValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests: Annotated[StrictInt, Field(ge=0)]
    input_tokens: Annotated[StrictInt | None, Field(ge=0)]
    output_tokens: Annotated[StrictInt | None, Field(ge=0)]


class ModelUsageStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    generation: ModelUsageValue
    embedding: ModelUsageValue


class ModelUsagePurposeBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    purpose: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    generation: ModelUsageValue
    embedding: ModelUsageValue


class ModelUsageDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    generation: ModelUsageValue
    embedding: ModelUsageValue
    by_purpose: Annotated[list[ModelUsagePurposeBreakdown], Field(max_length=16)]


class Timezone(StrEnum):
    UTC = "UTC"


class TokenEstimatorProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    estimator_id: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    version: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class RecallTokenValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preparations: Annotated[StrictInt, Field(ge=0)]
    ready_preparations: Annotated[StrictInt, Field(ge=0)]
    comparable_preparations: Annotated[StrictInt, Field(ge=0)]
    baseline_tokens: Annotated[StrictInt, Field(ge=0)]
    recalled_tokens: Annotated[StrictInt, Field(ge=0)]
    token_reduction: StrictInt


class RecallTokenDay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    preparations: Annotated[StrictInt, Field(ge=0)]
    ready_preparations: Annotated[StrictInt, Field(ge=0)]
    comparable_preparations: Annotated[StrictInt, Field(ge=0)]
    baseline_tokens: Annotated[StrictInt, Field(ge=0)]
    recalled_tokens: Annotated[StrictInt, Field(ge=0)]
    token_reduction: StrictInt


class WorkClaimBasis(StrEnum):
    DECLARED = "declared"
    VERIFIED = "verified"


class Schema(StrEnum):
    POWERCONTEXT_WORK_CONTRACT_V1 = "powercontext.work-contract.v1"


class Trust(StrEnum):
    UNTRUSTED_INPUT = "untrusted_input"


class InScopeItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class Exclusion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class CompletionCriterion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class AuthorizationNote(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class OpenQuestion(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class Schema1(StrEnum):
    POWERCONTEXT_CURRENT_WORK_HANDOFF_V1 = "powercontext.current-work-handoff.v1"


class Omission(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class WorkSourceKind(StrEnum):
    WORK_CONTRACT = "work-contract"
    HANDOFF_BOUNDARY = "handoff-boundary"
    HANDOFF_RECEIPT = "handoff-receipt"
    TASK_OUTCOME = "task-outcome"


class HandoffReceiptStatus(StrEnum):
    ACCEPTED = "accepted"
    NEEDS_CLARIFICATION = "needs_clarification"
    DECLINED = "declined"


class HandoffAcknowledgementSelection(StrEnum):
    PREPARED = "prepared"
    EXACT = "exact"


class LiveStateCheckStatus(StrEnum):
    CONFIRMED = "confirmed"
    MISMATCH = "mismatch"
    NOT_CHECKED = "not_checked"


class ReceiverReadinessCheckStatus(StrEnum):
    CONFIRMED = "confirmed"
    INSUFFICIENT = "insufficient"
    NOT_CHECKED = "not_checked"


class ReceiverChecks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    live_state: LiveStateCheckStatus
    capability: ReceiverReadinessCheckStatus
    authorization: ReceiverReadinessCheckStatus


class TaskOutcomeStatus(StrEnum):
    SUCCEEDED = "succeeded"
    PARTIAL = "partial"
    BLOCKED = "blocked"
    FAILED = "failed"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"


class TaskCheckStatus(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"
    TIMED_OUT = "timed_out"
    UNAVAILABLE = "unavailable"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"


class Schema2(StrEnum):
    POWERCONTEXT_TASK_OUTCOME_V1 = "powercontext.task-outcome.v1"


class Trust2(StrEnum):
    UNTRUSTED_OBSERVATION = "untrusted_observation"


class RemainingWorkItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class CaptureContentSourceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    content: Annotated[StrictStr, Field(max_length=200000, min_length=1)]
    metadata: dict[str, Any] | None = None


class SourceProjectionKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    version: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]


class SourceProjectionManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: SourceProjectionKey
    schema_: Annotated[dict[str, Any], Field(alias="schema")]


class SourceDefinitionManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    version: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    fingerprint: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]
    source_schema: dict[str, Any]
    projections: Annotated[list[SourceProjectionManifest], Field(max_length=16)]


class RegisterSourceDefinitionRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    manifest: SourceDefinitionManifest


class ConnectorBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    binding_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    connector_name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    connector_version: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]


class GetConnectorCheckpointRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding: ConnectorBinding


class ConnectorCheckpointState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding: ConnectorBinding
    checkpoint: Annotated[Any | None, Field(...)]


class SourceProjectionValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: SourceProjectionKey
    value: Any


class Materialization(StrEnum):
    CAPTURED = "captured"


class SourceObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    definition_version: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    materialization: Materialization
    description: StrictStr | None = None
    source_type: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    definition_fingerprint: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]
    payload: dict[str, Any]
    projections: Annotated[list[SourceProjectionValue], Field(max_length=16)]


class SubmitSourceObservationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    observation: SourceObservation


class CommitConnectorCheckpointRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding: ConnectorBinding
    expected: Annotated[Any | None, Field(...)]
    checkpoint: Annotated[Any | None, Field(...)]


class Kind(StrEnum):
    ARTIFACT = "artifact"


class HandoffArtifactCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["artifact"]
    artifact_ref: ArtifactReference


class Kind1(StrEnum):
    MEMORY = "memory"


class Trust3(StrEnum):
    UNTRUSTED_HISTORY = "untrusted_history"


class Kind2(StrEnum):
    SOURCE = "source"


class ExperienceProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    situation: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    action: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    outcome: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]
    lesson: Annotated[StrictStr, Field(max_length=8000, min_length=1, pattern=".*\\S.*")]


class SkillLifecycleState(StrEnum):
    ACTIVE = "active"
    DEPRECATED = "deprecated"
    RETIRED = "retired"


class SkillGovernance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    lifecycle_state: SkillLifecycleState
    replacement_artifact_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1)]
    governance_generation: Annotated[StrictInt, Field(ge=0)]


class ListManagedSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None
    include_deprecated: StrictBool = False
    limit: Annotated[StrictInt, Field(ge=1, le=200)] = 100


class UpdateSkillLifecycleRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_generation: Annotated[StrictInt, Field(ge=0)]
    lifecycle_state: SkillLifecycleState
    replacement_artifact_id: Annotated[
        StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")
    ] = None


class SkillPackageReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tree_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    archive_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    file_count: Annotated[StrictInt, Field(ge=1, le=256)]
    uncompressed_size: Annotated[StrictInt, Field(ge=1, le=4194304)]
    archive_size: Annotated[StrictInt, Field(ge=1, le=5242880)]


class SkillPackageFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[StrictStr, Field(max_length=512, min_length=1)]
    digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    size: Annotated[StrictInt, Field(ge=0, le=4194304)]
    media_type: Annotated[StrictStr, Field(max_length=255, min_length=1)]
    executable: StrictBool


class SkillPackageManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package: SkillPackageReference
    name: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    description: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    license: Annotated[StrictStr | None, Field(max_length=512, min_length=1)] = None
    compatibility: Annotated[StrictStr | None, Field(max_length=500, min_length=1)] = None
    metadata: Annotated[dict[str, StrictStr], Field(max_length=64)]
    allowed_tools: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None
    files: Annotated[list[SkillPackageFile], Field(max_length=256, min_length=1)]


class GetSkillPackageRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class SkillPackageDownload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    package: SkillPackageReference
    archive_base64: Annotated[StrictStr, Field(max_length=6990508, min_length=1, pattern="^[A-Za-z0-9+/]*={0,2}$")]


class RemoteAgentKind(StrEnum):
    CODEX = "codex"
    CLAUDE_CODE = "claude_code"


class RemoteSkillTargetState(StrEnum):
    PENDING = "pending"
    ACTIVE = "active"
    REVOKED = "revoked"


class InstallationScope(StrEnum):
    PROJECT = "project"


class DeliveryMode(StrEnum):
    AGENT_PULL = "agent_pull"


class RemoteSkillTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    display_name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    agent_kind: RemoteAgentKind
    installation_scope: InstallationScope
    delivery_mode: DeliveryMode
    installation_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1)]
    state: RemoteSkillTargetState
    receiver_version: Annotated[StrictStr | None, Field(max_length=64, min_length=1)]
    environment_fingerprint: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")]
    machine_hostname: Annotated[StrictStr | None, Field(max_length=255, min_length=1, pattern=".*\\S.*")]
    workspace_name: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    last_seen_at: Annotated[AwareDatetime | None, Field(...)]
    generation: Annotated[StrictInt, Field(ge=0)]


class ListRemoteSkillTargetsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    target_id: Annotated[StrictStr | None, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")] = (
        None
    )
    limit: Annotated[StrictInt, Field(ge=1, le=200)] = 100


class CreateRemoteSkillTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    agent_kind: RemoteAgentKind
    display_name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]


class RemoteSkillTargetEnrollment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target: RemoteSkillTarget
    enrollment_code: Annotated[StrictStr, Field(max_length=256, min_length=32)]
    enrollment_expires_at: AwareDatetime


class EnrollRemoteSkillTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enrollment_code: Annotated[StrictStr, Field(max_length=256, min_length=32)]
    installation_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    receiver_version: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    environment_fingerprint: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")] = None
    machine_hostname: Annotated[StrictStr | None, Field(max_length=255, min_length=1, pattern=".*\\S.*")] = None
    workspace_name: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern=".*\\S.*")] = None


class RemoteSkillTargetCredential(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    agent_kind: RemoteAgentKind
    credential: Annotated[StrictStr, Field(max_length=256, min_length=32)]


class RevokeRemoteSkillTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    expected_generation: Annotated[StrictInt, Field(ge=0)]


class RenameRemoteSkillTargetRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    display_name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    expected_generation: Annotated[StrictInt, Field(ge=0)]


class PublishRemoteSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    artifact: ArtifactReference
    expected_generation: Annotated[StrictInt | None, Field(ge=0)]
    allow_deprecated: StrictBool = False


class UnpublishRemoteSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    target_id: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_generation: Annotated[StrictInt, Field(ge=0)]


class RemoteSkillDesiredState(StrEnum):
    PUBLISHED = "published"
    UNPUBLISHED = "unpublished"


class RemoteSkillPublicationState(StrEnum):
    UNPUBLISHED = "unpublished"
    PENDING = "pending"
    CURRENT = "current"
    UPDATE_AVAILABLE = "update_available"
    DELIVERY_FAILED = "delivery_failed"
    CONFLICT = "conflict"
    DRIFTED = "drifted"
    INCOMPATIBLE = "incompatible"


class RemoteSkillPublication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: StrictStr
    target_id: StrictStr
    artifact_id: StrictStr
    desired_state: RemoteSkillDesiredState
    desired_revision: Annotated[StrictInt, Field(ge=1)]
    desired_tree_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    observed_revision: Annotated[StrictInt | None, Field(ge=1)]
    observed_tree_digest: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")]
    observed_generation: Annotated[StrictInt | None, Field(ge=0)]
    state: RemoteSkillPublicationState
    last_error_code: Annotated[StrictStr | None, Field(max_length=128, min_length=1)]
    observed_at: Annotated[AwareDatetime | None, Field(...)]
    generation: Annotated[StrictInt, Field(ge=0)]


class RemoteSkillObservation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    tree_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    actual_tree_digest: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")]
    skill_name: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    applied_generation: Annotated[StrictInt, Field(ge=0)]


class ReconcileRemoteSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observations: Annotated[list[RemoteSkillObservation], Field(max_length=256)]
    receiver_version: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    environment_fingerprint: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")] = None


class RemoteSkillOperation(StrEnum):
    INSTALL = "install"
    UNPUBLISH = "unpublish"


class RemoteSkillAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: RemoteSkillOperation
    generation: Annotated[StrictInt, Field(ge=0)]
    artifact: ArtifactReference
    tree_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    skill_name: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    package: Annotated[SkillPackageReference | None, Field(...)]
    expected_local: Annotated[RemoteSkillObservation | None, Field(...)]
    blocked_error_code: Annotated[StrictStr | None, Field(max_length=128, min_length=1)]


class ReconcileRemoteSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: StrictStr
    target_id: StrictStr
    actions: Annotated[list[RemoteSkillAction], Field(max_length=256)]


class DownloadRemoteSkillPackageRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    generation: Annotated[StrictInt, Field(ge=0)]
    artifact: ArtifactReference
    package: SkillPackageReference


class RemoteSkillReceiptOutcome(StrEnum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class RemoteSkillFailureState(StrEnum):
    DELIVERY_FAILED = "delivery_failed"
    CONFLICT = "conflict"
    DRIFTED = "drifted"
    INCOMPATIBLE = "incompatible"


class RecordRemoteSkillReceiptRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: RemoteSkillOperation
    generation: Annotated[StrictInt, Field(ge=0)]
    artifact: ArtifactReference
    expected_tree_digest: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    observed_tree_digest: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")]
    outcome: RemoteSkillReceiptOutcome
    failure_state: Annotated[RemoteSkillFailureState | None, Field(...)]
    error_code: Annotated[StrictStr | None, Field(max_length=128, min_length=1)]
    receiver_version: Annotated[StrictStr, Field(max_length=64, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    environment_fingerprint: Annotated[StrictStr | None, Field(pattern="^[0-9a-f]{64}$")]


class RemoteSkillReceiptResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accepted: StrictBool
    stale: StrictBool
    publication: RemoteSkillPublication


class ProposeSkillPackageRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    archive_base64: Annotated[StrictStr, Field(max_length=6990508, min_length=1, pattern="^[A-Za-z0-9+/]*={0,2}$")]
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None
    target: Annotated[
        ArtifactReference | None,
        Field(description="Exact managed Skill Revision replaced by this complete package Candidate."),
    ] = None


class Invoked(StrEnum):
    TRUE = "true"
    FALSE = "false"
    UNKNOWN = "unknown"


class Validation(StrEnum):
    PASSED = "passed"
    FAILED = "failed"
    UNKNOWN = "unknown"


class Outcome(StrEnum):
    SUCCESS = "success"
    FAILURE = "failure"
    UNKNOWN = "unknown"


class SkillValidationItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]


class Provider(StrEnum):
    CODEX = "codex"
    CLAUDE_CODE = "claude_code"


class AgentKind(StrEnum):
    CODEX = "codex"
    CLAUDE_CODE = "claude_code"


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: StrictStr
    message: StrictStr
    details: Annotated[dict[str, Any] | None, Field(...)]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorDetail


class FlushMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class GetArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class GetExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class GetSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    artifact: ArtifactReference


class ReportFormat(StrEnum):
    JSON = "json"
    MARKDOWN = "markdown"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: StrictStr


class ListMemoryChangesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    since_revision: Annotated[
        StrictInt | None,
        Field(
            description="Exclusive lower bound; 0 requests complete history from Revision 1. Positive nonexistent revisions are errors.",
            ge=0,
        ),
    ] = None


class ListMemoryEntriesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    include_inactive: Annotated[
        StrictBool, Field(description="Include inactive entries from the current Memory head for explicit audit.")
    ] = False


class ListExternalSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    include_unavailable: StrictBool = False


class MemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    entry_version_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class PrepareContextRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class SkillGenerationOrigin(StrEnum):
    EXPERIENCE = "experience"
    SOURCE = "source"
    USAGE = "usage"


class GeneratedCandidateStatus(StrEnum):
    PENDING = "pending"
    NO_OP = "no_op"


class ReadinessStatus(StrEnum):
    READY = "ready"
    DEGRADED = "degraded"
    NOT_READY = "not_ready"


class RememberMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None
    expected_revision: Annotated[StrictInt | None, Field(ge=1)] = None


class RetireMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class RejectArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    reason: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern=".*\\S.*")]


class ReviseMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation
    kind: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    text: Annotated[StrictStr, Field(description="Must not exceed 8192 UTF-8 bytes after normalization.", min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=512)] = None


class ScanExternalSkillsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class ResolveExternalSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    fingerprint: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]


class ExternalSkillImportMode(StrEnum):
    IMPORT = "import"
    FORK = "fork"


class ImportExternalSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    fingerprint: Annotated[
        StrictStr,
        Field(description="Exact package fingerprint captured into Source lineage.", pattern="^[0-9a-f]{64}$"),
    ]
    mode: ExternalSkillImportMode
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None


class OperationStatus(StrEnum):
    QUEUED = "queued"
    RUNNING = "running"
    RETRY_WAIT = "retry_wait"
    CANCELLING = "cancelling"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"


class OperationKind(StrEnum):
    MEMORY_FLUSH = "memory_flush"
    EXPERIENCE_INCUBATION = "experience_incubation"


class Type(StrEnum):
    MEMORY_FLUSH = "memory_flush"


class MemoryOperationResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["memory_flush"]
    previous_cursor: Annotated[StrictInt, Field(ge=0)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]
    current_cursor: Annotated[StrictInt, Field(ge=0)]
    processed_source_count: Annotated[StrictInt, Field(ge=0)]
    memory: ArtifactReference | None = None


class Type1(StrEnum):
    EXPERIENCE_INCUBATION = "experience_incubation"


class ExperienceOperationResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["experience_incubation"]
    previous_cursor: Annotated[StrictInt, Field(ge=0)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]
    current_cursor: Annotated[StrictInt, Field(ge=0)]
    processed_source_count: Annotated[StrictInt, Field(ge=0)]
    candidate_count: Annotated[StrictInt, Field(ge=0)]


class OperationError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    code: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class OperationRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: UUID
    kind: OperationKind
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1)]
    status: OperationStatus
    attempt_count: Annotated[StrictInt, Field(ge=0)]
    state_version: Annotated[StrictInt, Field(ge=1)]
    created_at: AwareDatetime
    updated_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    result: Annotated[MemoryOperationResult | ExperienceOperationResult | None, Field(discriminator="type")] = None
    error: OperationError | None = None


class OperationAccepted(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: UUID
    status: OperationStatus
    status_url: Annotated[StrictStr, Field(pattern="^/v1/operations/[0-9a-f-]{36}$")]


class OperationPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[OperationRecord], Field(max_length=100)]
    next_cursor: StrictStr | None = None


class ListOperationsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr | None, Field(max_length=256, min_length=1)] = None
    kind: OperationKind | None = None
    status: OperationStatus | None = None
    cursor: StrictStr | None = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class OperationMutationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_version: Annotated[StrictInt, Field(ge=1)]


class Family(StrEnum):
    MEMORY = "memory"


class Family1(StrEnum):
    EXPERIENCE = "experience"


class CreateExperienceArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Literal["experience"]
    content: ExperienceProposal


class Family2(StrEnum):
    SKILL = "skill"


class Family3(StrEnum):
    HANDOFF = "handoff"


class CreateMemoryArtifactEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[
        StrictStr,
        Field(
            description="Open application-defined Memory kind. Recommended values are fact, preference, decision, constraint, and working_note. The Server validates and preserves the supplied value; it never guesses or replaces it.",
            max_length=128,
            min_length=1,
            pattern=".*\\S.*",
        ),
    ]
    text: Annotated[
        StrictStr,
        Field(
            description="Durable non-empty Memory entry text used to create the Entry Version and search projection.",
            max_length=8192,
            min_length=1,
            pattern=".*\\S.*",
        ),
    ]


class SourceType(StrEnum):
    CONTENT = "content"


class CreateSourceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_type: SourceType = SourceType.CONTENT
    content: Annotated[Any, Field(description="JSON value persisted by the built-in content Source adapter.")]


class ListArtifactsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50
    cursor: Annotated[StrictStr | None, Field(max_length=4096, min_length=1)] = None


class ReplaceMemoryArtifactEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entry_id: Annotated[
        StrictStr | None,
        Field(
            description="Existing logical entry to revise. Omit to append a new entry.",
            max_length=128,
            min_length=1,
            pattern="^[\\x21-\\x7E]+$",
        ),
    ] = None
    kind: Annotated[
        StrictStr,
        Field(
            description="Open application-defined kind; the Server preserves the supplied value.",
            max_length=128,
            min_length=1,
            pattern=".*\\S.*",
        ),
    ]
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]


class ReplaceExperienceArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: ExperienceProposal


class SourceTypeReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_type: SourceType
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class SourceReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(description="Stable Source type.")]
    source_id: StrictStr


class CaptureStatus(StrEnum):
    ACCEPTED = "accepted"


class BaseArtifactFamily(StrEnum):
    MEMORY = "memory"
    EXPERIENCE = "experience"
    SKILL = "skill"
    HANDOFF = "handoff"


class StatsPeriod(StrEnum):
    TODAY = "today"
    FIELD_7D = "7d"
    FIELD_30D = "30d"


class CandidateFamily(StrEnum):
    EXPERIENCE = "experience"
    SKILL = "skill"


class ExternalSkillInstallationScope(StrEnum):
    USER = "user"
    PROJECT = "project"
    PLUGIN = "plugin"


class ExternalSkillResolutionStatus(StrEnum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"


class CandidateStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class PreparedContextSchema(StrEnum):
    POWERCONTEXT_PREPARED_CONTEXT_V1 = "powercontext.prepared-context.v1"


class PreparedContextStatus(StrEnum):
    READY = "ready"
    EMPTY = "empty"


class EntryChangeOperation(StrEnum):
    ADD = "add"
    REVISE = "revise"
    DEACTIVATE = "deactivate"
    REACTIVATE = "reactivate"


class FlushStatus(StrEnum):
    IDLE = "idle"
    PROCESSED = "processed"


class MemoryEntryState(StrEnum):
    ACTIVE = "active"
    INACTIVE = "inactive"


class MemoryMatchedBy(StrEnum):
    FTS = "fts"
    VECTOR = "vector"


class MemorySearchMode(StrEnum):
    AUTO = "auto"
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class MemoryUsedSearchMode(StrEnum):
    FTS = "fts"
    VECTOR = "vector"
    HYBRID = "hybrid"


class HandoffClaim(StrEnum):
    STATE = "state"
    NEXT_ACTION = "next_action"


class HandoffActivationStatus(StrEnum):
    GENERATED = "generated"
    IGNORED = "ignored"


class HandoffDisposition(StrEnum):
    CONTINUABLE = "continuable"
    BLOCKED = "blocked"
    COMPLETE = "complete"


class HandoffEvidenceStatus(StrEnum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"


class HandoffResolutionStatus(StrEnum):
    EMPTY = "empty"
    RESOLVED = "resolved"


class HandoffSchema(StrEnum):
    POWERCONTEXT_HANDOFF_V1 = "powercontext.handoff.v1"


class HandoffSelection(StrEnum):
    PREPARED = "prepared"
    EXACT = "exact"
    LATEST = "latest"


class PreparedHandoffSchema(StrEnum):
    POWERCONTEXT_PREPARED_HANDOFF_V1 = "powercontext.prepared-handoff.v1"


class Type2(StrEnum):
    USER = "user"
    SERVICE = "service"


class AccessPrincipal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["user", "service"]
    id: Annotated[StrictStr, Field(max_length=255, min_length=1)]
    description: Annotated[StrictStr | None, Field(max_length=255, min_length=1)] = None


class Type3(StrEnum):
    GROUP = "group"


class AccessGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["group"]
    id: Annotated[StrictStr, Field(max_length=255, min_length=1)]
    description: Annotated[StrictStr | None, Field(max_length=255, min_length=1)] = None


class AccessSubject(RootModel[AccessPrincipal | AccessGroup]):
    root: Annotated[AccessPrincipal | AccessGroup, Field(discriminator="type")]


class AccessControlMode(StrEnum):
    DISABLED = "disabled"
    ENFORCED = "enforced"


class AccessProviderCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    safe_resource_filtering: StrictBool
    multi_requirement_check: StrictBool
    relationship_management: StrictBool
    group_subjects: StrictBool
    multi_principal: StrictBool
    max_direct_resource_keys: Annotated[StrictInt, Field(ge=1, le=10000)]


class ShareUnit(StrEnum):
    ARTIFACT = "artifact"
    MEMORY_ENTRY = "memory_entry"


class AccessAction(StrEnum):
    SERVER_OBSERVE = "server.observe"
    SERVER_ADMIN = "server.admin"
    SCOPE_READ = "scope.read"
    SCOPE_CONTRIBUTE = "scope.contribute"
    SCOPE_REVIEW = "scope.review"
    SCOPE_DELEGATE = "scope.delegate"
    SCOPE_ADMIN = "scope.admin"
    ARTIFACT_READ = "artifact.read"
    ARTIFACT_WRITE = "artifact.write"
    ARTIFACT_SHARE = "artifact.share"
    HANDOFF_EVIDENCE_INSPECT = "handoff.evidence.inspect"
    HANDOFF_ACKNOWLEDGE = "handoff.acknowledge"
    PROMPT_USE = "prompt.use"


class AccessResourceType(StrEnum):
    SERVER = "server"
    SCOPE = "scope"
    ARTIFACT = "artifact"


class Type4(StrEnum):
    SERVER = "server"


class ServerAccessResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["server"]
    deployment_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class Type5(StrEnum):
    SCOPE = "scope"


class ScopeAccessResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["scope"]
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]


class MemoryEntryAccessSelectorType(StrEnum):
    MEMORY_ENTRY = "memory_entry"


class MemoryEntryAccessSelector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: MemoryEntryAccessSelectorType
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class AccessArtifactIdentity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]


class Type6(StrEnum):
    ARTIFACT = "artifact"


class ArtifactAccessResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["artifact"]
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    identity: AccessArtifactIdentity
    selector: MemoryEntryAccessSelector | None = None


class AccessResource(RootModel[ServerAccessResource | ScopeAccessResource | ArtifactAccessResource]):
    root: Annotated[ServerAccessResource | ScopeAccessResource | ArtifactAccessResource, Field(discriminator="type")]


class AccessDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed: StrictBool
    reason_code: Annotated[StrictStr, Field(max_length=64, min_length=1)]


class AccessRequirementMatch(StrEnum):
    ALL = "all"
    ANY = "any"


class AccessCheckRequirement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: AccessAction
    resource: AccessResource


class AccessCheckRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    match: AccessRequirementMatch
    requirements: Annotated[list[AccessCheckRequirement], Field(max_length=100, min_length=1)]


class AccessCheckResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed: StrictBool
    decisions: Annotated[list[AccessDecision], Field(max_length=100, min_length=1)]


class ListAccessResourcesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: AccessAction
    resource_type: AccessResourceType
    family: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None
    cursor: StrictStr | None = None
    limit: Annotated[StrictInt, Field(ge=1, le=500)] = 100


class AccessResourcePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[AccessResource], Field(max_length=500)]
    total: Annotated[StrictInt, Field(ge=0)]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class AccessRole(StrEnum):
    HANDOFF_VIEWER = "handoff.viewer"
    HANDOFF_RECEIVER = "handoff.receiver"
    ARTIFACT_VIEWER = "artifact.viewer"
    PROMPT_USER = "prompt.user"
    ARTIFACT_OWNER = "artifact.owner"
    SCOPE_VIEWER = "scope.viewer"
    SCOPE_CONTRIBUTOR = "scope.contributor"
    SCOPE_REVIEWER = "scope.reviewer"
    SCOPE_DELEGATOR = "scope.delegator"
    SCOPE_ADMIN = "scope.admin"
    SERVER_OBSERVER = "server.observer"
    SERVER_ADMIN = "server.admin"


class AccessRoleCardinality(StrEnum):
    MANY_PER_RESOURCE = "many_per_resource"
    ONE_PER_RESOURCE = "one_per_resource"


class ListAccessRolesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_type: AccessResourceType | None = None
    family: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None


class ArtifactFamily(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=128, min_length=1)]


class AssignableSubjectType(StrEnum):
    USER = "user"
    SERVICE = "service"
    GROUP = "group"


class AccessRoleDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: AccessRole
    resource_type: AccessResourceType
    cardinality: AccessRoleCardinality
    actions: list[AccessAction]
    artifact_families: list[ArtifactFamily]
    assignable_subject_types: list[AssignableSubjectType]
    system_managed: StrictBool


class AccessRolePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[AccessRoleDescriptor], Field(max_length=16)]


class AccessBindingState(StrEnum):
    ACTIVE = "active"
    REVOKED = "revoked"


class AccessBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding_id: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    subject: AccessSubject
    resource: AccessResource
    role: AccessRole
    granted_by: AccessPrincipal
    reason: Annotated[StrictStr | None, Field(max_length=1024)]
    created_at: AwareDatetime
    expires_at: Annotated[AwareDatetime | None, Field(...)]
    state: AccessBindingState
    version: Annotated[StrictInt, Field(ge=1)]
    policy_revision: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    idempotency_key: Annotated[StrictStr, Field(max_length=255, min_length=1)]
    revoked_at: Annotated[AwareDatetime | None, Field(...)]
    revoked_by: Annotated[AccessPrincipal | None, Field(...)]


class ListAccessBindingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    management_resource: AccessResource
    subject: AccessSubject | None = None
    role: AccessRole | None = None
    state: AccessBindingState | None = None
    cursor: Annotated[StrictStr | None, Field(max_length=2048)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=500)] = 100


class AccessBindingPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[AccessBinding], Field(max_length=500)]
    next_cursor: Annotated[StrictStr | None, Field(max_length=2048)]


class CreateAccessBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: AccessSubject
    resource: AccessResource
    role: AccessRole
    idempotency_key: Annotated[StrictStr, Field(max_length=255, min_length=1)]
    reason: Annotated[StrictStr | None, Field(max_length=1024)] = None
    expires_at: AwareDatetime | None = None


class RevokeAccessBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding_id: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    idempotency_key: Annotated[StrictStr, Field(max_length=255, min_length=1)]


class AccessBindingReplacementInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: AccessSubject
    reason: Annotated[StrictStr | None, Field(max_length=1024)] = None
    expires_at: AwareDatetime | None = None


class ReplaceAccessBindingRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binding_id: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    replacement: AccessBindingReplacementInput
    idempotency_key: Annotated[StrictStr, Field(max_length=255, min_length=1)]


class AccessBindingReplacement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    previous: AccessBinding
    current: AccessBinding


class Result(StrEnum):
    ALLOWED = "allowed"
    DENIED = "denied"


class AccessAuditTimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: AwareDatetime
    end: AwareDatetime


class AccessAuditEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: Annotated[StrictInt, Field(ge=1)]
    event_id: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    occurred_at: AwareDatetime
    request_id: Annotated[StrictStr | None, Field(max_length=128)]
    transport: Annotated[StrictStr, Field(max_length=16, min_length=1)]
    operation: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    principal: AccessPrincipal
    actor: Annotated[AccessPrincipal | None, Field(...)]
    action: AccessAction
    resource: AccessResource
    allowed: StrictBool
    reason_code: Annotated[StrictStr, Field(max_length=64, min_length=1)]
    policy_revision: Annotated[StrictStr | None, Field(max_length=64, min_length=1)]
    matched_subject: Annotated[AccessSubject | None, Field(...)]
    binding_id: Annotated[StrictStr | None, Field(max_length=64)]
    target: Annotated[AccessSubject | None, Field(...)]
    role: Annotated[AccessRole | None, Field(...)]
    expected_version: Annotated[StrictInt | None, Field(ge=1)]
    result_version: Annotated[StrictInt | None, Field(ge=1)]


class AccessAuditPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[list[AccessAuditEvent], Field(max_length=500)]
    next_cursor: Annotated[StrictStr | None, Field(max_length=2048)]


class ArtifactCollectionItem(BaseModel):
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    family: BaseArtifactFamily
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]
    sources: list[SourceTypeReference]
    artifacts: list[ArtifactReference]
    content_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class ArtifactCreated(BaseModel):
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    family: BaseArtifactFamily
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]
    sources: list[SourceTypeReference]
    artifacts: list[ArtifactReference]


class ArtifactPage(BaseModel):
    items: list[ArtifactCollectionItem]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class ArtifactRevision(BaseModel):
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    family: BaseArtifactFamily
    artifact_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    revision: Annotated[StrictInt, Field(ge=1)]
    content: dict[str, Any]
    sources: list[SourceTypeReference]
    artifacts: list[ArtifactReference]
    content_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class HandoffReceiptIdentity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    principal: AccessPrincipal
    receiver_identity_matches: StrictBool


class Capabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_types: list[StrictStr]
    artifact_families: list[StrictStr]
    memory_extraction: Annotated[StrictBool, Field(description="Whether pending Sources can be extracted into Memory.")]
    experience_generation: Annotated[
        StrictBool, Field(description="Whether the configured model can generate reviewed Experience Candidates.")
    ] = False
    managed_skill_generation: Annotated[
        StrictBool, Field(description="Whether the configured model can generate reviewed managed Skill Candidates.")
    ] = False
    external_skill_registry: Annotated[
        StrictBool,
        Field(description="Whether host-local external Skill discovery and exact resolution are configured."),
    ] = False
    handoff_generation: Annotated[
        StrictBool, Field(description="Whether exact evidence can be generated into an inspectable Handoff Draft.")
    ]
    search_modes: list[MemorySearchMode]
    context_versions: list[PreparedContextSchema]


class CandidateFamilyCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: CandidateFamily
    total: Annotated[StrictInt, Field(ge=0)]
    pending: Annotated[StrictInt, Field(ge=0)]
    approved: Annotated[StrictInt, Field(ge=0)]
    rejected: Annotated[StrictInt, Field(ge=0)]


class CandidateInventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: Annotated[StrictInt, Field(ge=0)]
    pending: Annotated[StrictInt, Field(ge=0)]
    approved: Annotated[StrictInt, Field(ge=0)]
    rejected: Annotated[StrictInt, Field(ge=0)]
    by_family: list[CandidateFamilyCount]


class InventoryStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sources: SourceInventoryStatistics
    artifacts: ArtifactInventoryStatistics
    candidates: CandidateInventoryStatistics
    memory: MemoryInventoryStatistics


class ResolvedUsagePeriod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preset: StatsPeriod
    start_date: date_aliased
    end_date: date_aliased
    timezone: Timezone


class UsageStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    period: ResolvedUsagePeriod
    totals: ModelUsageStatistics
    by_purpose: Annotated[list[ModelUsagePurposeBreakdown], Field(max_length=16)]
    daily: Annotated[list[ModelUsageDay], Field(max_length=30)]


class RecallTokenStatistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    period: ResolvedUsagePeriod
    estimator: Annotated[TokenEstimatorProfile | None, Field(...)]
    totals: RecallTokenValue
    daily: Annotated[list[RecallTokenDay], Field(max_length=30)]


class ScopeStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: StrictStr
    inventory: InventoryStatistics
    usage: UsageStatistics
    recall: RecallTokenStatistics


class ScopedStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selection: ScopeSelection
    scope_ids: list[StrictStr]
    as_of: AwareDatetime
    inventory: InventoryStatistics
    usage: UsageStatistics
    recall: RecallTokenStatistics
    by_scope: list[ScopeStats]


class GetStatsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selection: ScopeSelection
    period: StatsPeriod = StatsPeriod.FIELD_30D


class WorkSourceReceipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: WorkSourceKind
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]
    content_digest: Annotated[StrictStr, Field(max_length=71, min_length=71, pattern="^sha256:[0-9a-f]{64}$")]


class CaptureContentSourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: CaptureStatus
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]


class SourceObservationReceipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: SourceReference
    position: Annotated[StrictInt, Field(ge=1)]


class HandoffMemoryCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["memory"]
    memory_citation: MemoryCitation


class HandoffSourceCitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["source"]
    source_ref: SourceReference


class PreparedContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[PreparedContextSchema, Field(alias="schema")]
    status: PreparedContextStatus
    content: Annotated[StrictStr | None, Field(...)]
    content_bytes: Annotated[StrictInt, Field(ge=0)]


class EntryChange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: EntryChangeOperation
    entry_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    from_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    to_entry_version_id: Annotated[StrictStr | None, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    reason: Annotated[StrictStr | None, Field(...)]


class ExperienceArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: ExperienceProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class SkillProposal(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    description: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    instructions: Annotated[StrictStr, Field(max_length=131072)]
    validation: Annotated[list[SkillValidationItem], Field(max_length=32)]
    package: SkillPackageReference | None = None
    license: Annotated[StrictStr | None, Field(max_length=512, min_length=1)] = None
    compatibility: Annotated[StrictStr | None, Field(max_length=500, min_length=1)] = None
    metadata: Annotated[dict[str, StrictStr] | None, Field(max_length=64)] = None
    allowed_tools: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None


class RemoteSkillTargetStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    target: RemoteSkillTarget
    publications: Annotated[list[RemoteSkillPublication], Field(max_length=256)]


class ListRemoteSkillTargetsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    targets: Annotated[list[RemoteSkillTargetStatus], Field(max_length=200)]


class RecordSkillUsageRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    observation_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    skill_ref: ArtifactReference
    package_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]
    target_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern=".*\\S.*")]
    selected: StrictBool
    invoked: Invoked
    validation: Validation
    outcome: Outcome
    task_source: SourceReference | None = None
    environment_fingerprint: Annotated[StrictStr | None, Field(pattern="^sha256:[0-9a-f]{64}$")] = None


class ExternalSkillRegistration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    external_skill_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    provider: Provider
    agent_kind: AgentKind
    host_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    installation_scope: ExternalSkillInstallationScope
    locator: Annotated[
        StrictStr,
        Field(
            description="Host-local locator; not a cross-Agent or cross-host contract.",
            max_length=2000,
            min_length=1,
            pattern="^\\S(?:.*\\S)?$",
        ),
    ]
    fingerprint: Annotated[StrictStr, Field(pattern="^[0-9a-f]{64}$")]
    name: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^\\S(?:.*\\S)?$")]
    description: Annotated[StrictStr, Field(max_length=2000, min_length=1, pattern="^\\S(?:.*\\S)?$")]


class ExternalSkillResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registration: ExternalSkillRegistration
    status: ExternalSkillResolutionStatus
    entrypoint: Annotated[
        StrictStr | None,
        Field(description="Host-local SKILL.md path; present only when the exact fingerprint is available."),
    ]


class ScanExternalSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registrations: list[ExternalSkillRegistration]
    skipped: Annotated[StrictInt, Field(ge=0)]


class ListExternalSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skills: list[ExternalSkillResolution]


class FlushMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: FlushStatus
    previous_cursor: Annotated[StrictInt, Field(ge=0)]
    current_cursor: Annotated[StrictInt, Field(ge=0)]
    high_watermark: Annotated[StrictInt, Field(ge=0)]
    processed_source_count: Annotated[StrictInt, Field(ge=0)]
    memory: ArtifactReference | None = None


class GetMemoryEntryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    citation: MemoryCitation


class GetHandoffReportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selection: ScopeSelection
    format: ReportFormat = ReportFormat.JSON
    download: StrictBool = False


class HandoffReportResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: ReportFormat
    report: Annotated[dict[str, Any] | None, Field(...)]
    markdown: Annotated[StrictStr | None, Field(...)]
    selection_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]
    report_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class ListArtifactCandidatesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    status: CandidateStatus = CandidateStatus.PENDING
    family: CandidateFamily | None = None
    cursor: Annotated[StrictStr | None, Field(max_length=128, min_length=1)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=100)] = 50


class MemoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    version: Annotated[StrictInt, Field(ge=1)]
    kind: StrictStr
    text: StrictStr
    state: MemoryEntryState
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class MemoryMutationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference
    entry: MemoryEntry | None = None


class MemoryRevisionChanges(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory_ref: ArtifactReference
    changes: list[EntryChange]


class ProposeExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    proposal: ExperienceProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class GenerateExperienceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ProposeSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    proposal: SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class GenerateSkillRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    origin: SkillGenerationOrigin
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ReadinessResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: ReadinessStatus
    checks: dict[str, StrictStr]


class ReviseArtifactCandidateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    expected_version: Annotated[StrictInt, Field(ge=1)]
    proposal: ExperienceProposal | SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: ArtifactReference | None = None
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)] = None

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class SearchMemoryHit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    citation: MemoryCitation
    text: StrictStr
    score: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    matched_by: list[MemoryMatchedBy]


class SearchMemoryRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    query: Annotated[StrictStr, Field(max_length=8192, min_length=1)]
    limit: Annotated[StrictInt, Field(ge=1, le=50)] = 10
    mode: MemorySearchMode = MemorySearchMode.AUTO


class SearchMemoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    mode: MemoryUsedSearchMode | None = None
    hits: list[SearchMemoryHit]


class CreateSkillArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Literal["skill"]
    content: SkillProposal


class CreateMemoryArtifactContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: Annotated[list[CreateMemoryArtifactEntry], Field(max_length=100, min_length=1)]


class ReplaceMemoryArtifactContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: Annotated[list[ReplaceMemoryArtifactEntry], Field(max_length=100, min_length=1)]


class ReplaceSkillArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: SkillProposal


class SourceRecord(BaseModel):
    receipt_identity: Annotated[
        HandoffReceiptIdentity | None,
        Field(
            description="Server-owned identity attestation when this Source contains an enforced-mode Handoff Receipt."
        ),
    ] = None
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_type: SourceType
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    content: Annotated[Any, Field(description="Persisted canonical JSON content.")]
    position: Annotated[StrictInt, Field(ge=1)]
    content_digest: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class ArtifactFamilyAccessCapability(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Annotated[StrictStr, Field(max_length=128, min_length=1)]
    enabled: StrictBool
    share_unit: ShareUnit
    actions: list[AccessAction]
    grantable_roles: list[AccessRole]


class AccessMeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    principal: AccessPrincipal
    mode: AccessControlMode
    resource_kinds: list[AccessResourceType]
    provider_capabilities: AccessProviderCapabilities
    artifact_families: list[ArtifactFamilyAccessCapability]


class ListAccessAuditRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: Annotated[ServerAccessResource | ScopeAccessResource, Field(discriminator="type")]
    action: AccessAction | None = None
    subject: AccessSubject | None = None
    result: Result | None = None
    time_range: AccessAuditTimeRange | None = None
    cursor: Annotated[StrictStr | None, Field(max_length=2048)] = None
    limit: Annotated[StrictInt, Field(ge=1, le=500)] = 100


class ArtifactCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: Annotated[
        CandidatePermissions | None,
        Field(description="Current Principal permissions in enforced mode; advisory and checked again on mutation."),
    ] = None
    candidate_id: Annotated[StrictStr, Field(max_length=128, min_length=1, pattern="^[\\x21-\\x7E]+$")]
    version: Annotated[StrictInt, Field(ge=1)]
    family: CandidateFamily
    status: CandidateStatus
    proposal: ExperienceProposal | SkillProposal
    source_refs: Annotated[
        list[SourceReference],
        Field(
            description="Exact Source evidence. Counted with artifact_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    artifact_refs: Annotated[
        list[ArtifactReference],
        Field(
            description="Exact Artifact evidence. Counted with source_refs toward a combined maximum of 32 references.",
            max_length=32,
        ),
    ]
    target: Annotated[ArtifactReference | None, Field(...)]
    reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]
    result_artifact: Annotated[ArtifactReference | None, Field(...)]
    decision_reason: Annotated[StrictStr | None, Field(max_length=2000, min_length=1)]

    @model_validator(mode="after")
    def _reject_excess_candidate_evidence(self):
        if len(self.source_refs) + len(self.artifact_refs) > 32:
            raise ValueError(  # noqa: TRY003
                "source_refs and artifact_refs together must not exceed 32 references"
            )
        return self


class ArtifactCandidatePage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidates: list[ArtifactCandidate]
    next_cursor: Annotated[StrictStr | None, Field(...)]


class HandoffCitation(RootModel[HandoffSourceCitation | HandoffArtifactCitation | HandoffMemoryCitation]):
    root: Annotated[
        HandoffSourceCitation | HandoffArtifactCitation | HandoffMemoryCitation, Field(discriminator="kind")
    ]


class HandoffEvidenceCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claim: HandoffClaim
    state_index: Annotated[StrictInt | None, Field(ge=0)]
    status: HandoffEvidenceStatus
    unavailable_evidence: Annotated[list[HandoffCitation], Field(max_length=32)]


class HandoffOmission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    citation: Annotated[HandoffCitation | None, Field(...)]


class HandoffStatement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    citations: Annotated[list[HandoffCitation], Field(max_length=32, min_length=1)]


class PrepareHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    evidence: Annotated[list[HandoffCitation], Field(max_length=32, min_length=1)]
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class SkillArtifact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: SkillProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class ManagedSkillLibraryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactReference
    content: SkillProposal
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]
    governance: SkillGovernance


class ListManagedSkillsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skills: Annotated[list[ManagedSkillLibraryEntry], Field(max_length=200)]


class ListMemoryChangesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    revisions: list[MemoryRevisionChanges]


class ListMemoryEntriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    memory: ArtifactReference | None = None
    entries: list[MemoryEntry]


class GeneratedCandidateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: GeneratedCandidateStatus
    candidate: Annotated[ArtifactCandidate | None, Field(...)]


class CreateMemoryArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Literal["memory"]
    content: CreateMemoryArtifactContent


class ReplaceMemoryArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: ReplaceMemoryArtifactContent


class ActivateHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    boundary_source: SourceReference
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    evidence: Annotated[list[HandoffCitation], Field(max_length=32, validate_default=True)] = []
    max_bytes: Annotated[StrictInt, Field(ge=512, le=32768)] = 8000


class WorkClaim(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    basis: WorkClaimBasis
    evidence: Annotated[list[HandoffCitation], Field(max_length=31)]


class WorkContract(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema, Field(alias="schema")]
    trust: Trust
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    facts: Annotated[list[WorkClaim], Field(max_length=64)]
    in_scope: Annotated[list[InScopeItem], Field(max_length=64, min_length=1)]
    exclusions: Annotated[list[Exclusion], Field(max_length=64)]
    completion_criteria: Annotated[list[CompletionCriterion], Field(max_length=64, min_length=1)]
    authorization_notes: Annotated[list[AuthorizationNote], Field(max_length=64)]
    open_questions: Annotated[list[OpenQuestion], Field(max_length=64)]


class CreateWorkContractRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    contract: WorkContract


class CurrentWorkHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema1, Field(alias="schema")]
    trust: Trust
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[WorkClaim], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[WorkClaim | None, Field(...)]
    omissions: Annotated[list[Omission], Field(max_length=64)]


class HandoffCurrentWorkRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    handoff: CurrentWorkHandoff


class TaskCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    status: TaskCheckStatus
    details: Annotated[StrictStr | None, Field(max_length=8192, min_length=1, pattern=".*\\S.*")] = None
    basis: WorkClaimBasis
    evidence: Annotated[list[HandoffCitation], Field(max_length=32)]


class TaskOutcome(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[Schema2, Field(alias="schema")]
    trust: Trust2
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    status: TaskOutcomeStatus
    summary: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    handoff_receipt_ref: SourceReference | None = None
    observations: Annotated[list[WorkClaim], Field(max_length=64, min_length=1)]
    checks: Annotated[list[TaskCheck], Field(max_length=64)]
    produced_artifacts: Annotated[list[ArtifactReference], Field(max_length=32)]
    remaining_work: Annotated[list[RemainingWorkItem], Field(max_length=64)]


class RecordTaskOutcomeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    outcome: TaskOutcome


class HandoffContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[HandoffSchema, Field(alias="schema")]
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[HandoffStatement], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[HandoffStatement | None, Field(...)]
    omissions: Annotated[list[HandoffOmission], Field(max_length=64)]


class HandoffDraft(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    objective: Annotated[StrictStr, Field(max_length=8192, min_length=1, pattern=".*\\S.*")]
    state: Annotated[list[HandoffStatement], Field(max_length=64, min_length=1)]
    disposition: HandoffDisposition
    next_action: Annotated[HandoffStatement | None, Field(...)]
    omissions: Annotated[list[HandoffOmission], Field(max_length=64)]


class HandoffResolution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trust: Trust3
    status: HandoffResolutionStatus
    scope_id: StrictStr
    content: Annotated[HandoffContent | None, Field(...)]
    selection: Annotated[HandoffSelection | None, Field(...)]
    selected_revision: Annotated[ArtifactReference | None, Field(...)]
    current_revision: Annotated[ArtifactReference | None, Field(...)]
    evidence_checks: Annotated[list[HandoffEvidenceCheck], Field(max_length=65)]


class PreparedHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_: Annotated[PreparedHandoffSchema, Field(alias="schema")]
    scope_id: StrictStr
    base: Annotated[ArtifactReference | None, Field(...)]
    content: HandoffContent


class CreateHandoffArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    family: Literal["handoff"]
    content: HandoffContent


class ReplaceHandoffArtifactRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content: HandoffContent


class PreparedWorkHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    boundary: WorkSourceReceipt
    handoff: PreparedHandoff


class AcknowledgeHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    source_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    receiver: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    status: HandoffReceiptStatus
    selection: HandoffAcknowledgementSelection
    receiver_checks: ReceiverChecks | None = None
    prepared: PreparedHandoff | None = None
    revision: ArtifactReference | None = None
    message: Annotated[StrictStr | None, Field(max_length=8192, min_length=1, pattern=".*\\S.*")] = None


class HandoffAcknowledgement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    receipt_identity: HandoffReceiptIdentity | None = None
    resolution: HandoffResolution
    receipt: WorkSourceReceipt


class CommitHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    handoff: PreparedHandoff


class CommittedHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reference: ArtifactReference
    content: HandoffContent
    source_refs: list[SourceReference]
    artifact_refs: list[ArtifactReference]


class ContinueHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    selection: HandoffSelection
    prepared: PreparedHandoff | None = None
    revision: ArtifactReference | None = None


class FinalizeHandoffRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope_id: Annotated[StrictStr, Field(max_length=256, min_length=1, pattern=".*\\S.*")]
    draft: HandoffDraft


class HandoffActivation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: HandoffActivationStatus
    boundary_source: SourceReference
    previous_position: Annotated[StrictInt, Field(ge=0)]
    current_position: Annotated[StrictInt, Field(ge=0)]
    draft: Annotated[HandoffDraft | None, Field(...)]


class CreateArtifactRequest(
    RootModel[
        CreateMemoryArtifactRequest
        | CreateExperienceArtifactRequest
        | CreateSkillArtifactRequest
        | CreateHandoffArtifactRequest
    ]
):
    root: Annotated[
        CreateMemoryArtifactRequest
        | CreateExperienceArtifactRequest
        | CreateSkillArtifactRequest
        | CreateHandoffArtifactRequest,
        Field(discriminator="family"),
    ]


class ReplaceArtifactRequest(
    RootModel[
        ReplaceMemoryArtifactRequest
        | ReplaceExperienceArtifactRequest
        | ReplaceSkillArtifactRequest
        | ReplaceHandoffArtifactRequest
    ]
):
    root: (
        ReplaceMemoryArtifactRequest
        | ReplaceExperienceArtifactRequest
        | ReplaceSkillArtifactRequest
        | ReplaceHandoffArtifactRequest
    )
