name: Deploy website

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-website:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Set up website tools
        uses: jdx/mise-action@v2

      - name: Build website
        run: make docs-build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: website/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
